# template.yaml – AI News Pipeline with environment parameters for Lambda

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda deployment for AI Research Poster Pipeline

Parameters:
  S3OutputBucket:
    Type: String
    Description: S3 bucket used for storing output data

  ScraperOutputPrefix:
    Type: String
    Default: ai-research-pipeline/output/scraper/
    Description: Prefix for scraper output

  SummarizerOutputPrefix:
    Type: String
    Default: ai-research-pipeline/output/summarizer/
    Description: Prefix for summarizer output

  PosterOutputPrefix:
    Type: String
    Default: ai-research-pipeline/output/poster/
    Description: Prefix for poster output

  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-5-sonnet-20240620-v1:0
    Description: Bedrock model to use for summarization

  FinalSummarizedFile:
    Type: String
    Default: final_summarized.json
    Description: Name of the reassembled summary output file

  MemoryOutputPrefix:
    Type: String
    Default: ai-research-pipeline/output/memory/
    Description: Prefix for memory output

  MemoryOutputFile:
    Type: String
    Default: article_memory.json
    Description: Key for memory output file

Globals:
  Function:
    Timeout: 600
    Runtime: python3.11
    MemorySize: 512

Resources:

  CommonUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-utils
      Description: Shared utility code for all AI pipeline Lambdas
      ContentUri: lambda/layers/common
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  PipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-research-pipeline
      Handler: pipeline_lambda.handler
      CodeUri: lambda/pipeline/
      Layers:
        - !Ref CommonUtilsLayer
      Description: Full pipeline controller of scraper → summarizer → poster
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt ScraperFunction.Arn
                - !GetAtt SummarizerMainFunction.Arn
                - !GetAtt PosterFunction.Arn
      Environment:
        Variables:
          S3_OUTPUT_BUCKET: !Ref S3OutputBucket
          SCRAPER_FUNCTION_NAME: !Ref ScraperFunction
          SUMMARIZER_MAIN_FUNCTION_NAME: !Ref SummarizerMainFunction
          POSTER_FUNCTION_NAME: !Ref PosterFunction

  ScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-research-scraper
      Handler: scraper_lambda.handler
      CodeUri: lambda/scraper/
      Layers:
        - !Ref CommonUtilsLayer
      Description: Scrapes articles
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:s3:::${S3OutputBucket}
                - !Sub arn:aws:s3:::${S3OutputBucket}/${ScraperOutputPrefix}*
                - !Sub arn:aws:s3:::${S3OutputBucket}/${MemoryOutputPrefix}${MemoryOutputFile}
      Environment:
        Variables:
          S3_OUTPUT_BUCKET: !Ref S3OutputBucket
          SCRAPER_OUTPUT_PREFIX: !Ref ScraperOutputPrefix
          MEMORY_OUTPUT_PREFIX: !Ref MemoryOutputPrefix
          MEMORY_OUTPUT_FILE: !Ref MemoryOutputFile

  SummarizerMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-research-summarizer-main
      Handler: summarizer_main_lambda.handler
      CodeUri: lambda/summarizer/
      Layers:
        - !Ref CommonUtilsLayer
      Description: Controller for chunking and summarization of scraped data in parallel (run this, not summarizer)
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:s3:::${S3OutputBucket}
                - !Sub arn:aws:s3:::${S3OutputBucket}/${ScraperOutputPrefix}*
                - !Sub arn:aws:s3:::${S3OutputBucket}/${SummarizerOutputPrefix}*
                - !GetAtt SummarizerFunction.Arn  # Needed for invoking summarizer within main controller
      Environment:
        Variables:
          S3_OUTPUT_BUCKET: !Ref S3OutputBucket
          SCRAPER_OUTPUT_PREFIX: !Ref ScraperOutputPrefix
          SUMMARIZER_OUTPUT_PREFIX: !Ref SummarizerOutputPrefix
          SUMMARIZER_FUNCTION_NAME: !Ref SummarizerFunction


  SummarizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-research-summarizer
      Handler: summarizer_lambda.handler
      CodeUri: lambda/summarizer/
      Layers:
        - !Ref CommonUtilsLayer
      Description: Summarizes articles using Bedrock & FMs
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:ListFoundationModels
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0
                - !Sub arn:aws:s3:::${S3OutputBucket}
                - !Sub arn:aws:s3:::${S3OutputBucket}/${ScraperOutputPrefix}*
                - !Sub arn:aws:s3:::${S3OutputBucket}/${SummarizerOutputPrefix}*
      Environment:
        Variables:
          S3_OUTPUT_BUCKET: !Ref S3OutputBucket
          SCRAPER_OUTPUT_PREFIX: !Ref ScraperOutputPrefix
          SUMMARIZER_OUTPUT_PREFIX: !Ref SummarizerOutputPrefix
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      

  PosterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ai-research-poster
      Handler: poster_lambda.handler
      CodeUri: lambda/poster/
      Description: Posts summaries to Twitter as threads
      Layers:
        - !Ref CommonUtilsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:secretsmanager:us-east-1:894495940143:secret:TwitterAPICreds-n5vtOF
                - !Sub arn:aws:s3:::${S3OutputBucket}
                - !Sub arn:aws:s3:::${S3OutputBucket}/${SummarizerOutputPrefix}*
      Environment:
        Variables:
          S3_OUTPUT_BUCKET: !Ref S3OutputBucket
          SUMMARY_OUTPUT_PREFIX: !Ref SummarizerOutputPrefix
          SUMMARIZED_FILE: !Ref FinalSummarizedFile

  PipelineSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: pipeline-daily-run
      ScheduleExpression: cron(0 0,4,8,12,16,20 ? * MON-FRI *) # Every 4 hours on weekdays
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt PipelineFunction.Arn
        RoleArn: !GetAtt SchedulerInvokeRole.Arn
        Input: !Sub |
          {
            "scrape_limit": 1,
            "chunk_size": 1,
            "skip_memory": false,
            "dry_run": false
          }

  SchedulerInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SchedulerInvokeRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowLambdaInvoke
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt PipelineFunction.Arn      

Outputs:
  SummarizerMainOutput:
    Description: Summarizer Main Lambda Function ARN
    Value: !GetAtt SummarizerMainFunction.Arn
  PosterOutput:
    Description: Poster Lambda Function ARN
    Value: !GetAtt PosterFunction.Arn
  SummarizerOutput:
    Description: Summarizer Lambda Function ARN
    Value: !GetAtt SummarizerFunction.Arn
  ScraperOutput:
    Description: Scraper Lambda Function ARN
    Value: !GetAtt ScraperFunction.Arn
